feat: add image options
hexojs/hexo-renderer-markdown-it pull request #188
Opened 2022-08-31 11:13 UTC by renbaoshuo

This pull request resolves #140, closes #141.

2022-08-31 15:00 UTC, SukkaW approved these changes

2022-08-31 15:01 UTC, SukkaW requested changes
CI fails on windows. Do you have any clues?

2022-08-31 23:21 UTC, renbaoshuo commented
> CI fails on windows. Do you have any clues?

Nope.

2022-09-03 14:21 UTC, renbaoshuo commented
Is there anyone who has windows environment can help to resolve the failures on CI?

2022-09-04 07:29 UTC, renbaoshuo commented
> CI fails on windows. Do you have any clues?

Fixed in 43dc603a8780b93b00cfcccb48672af494598ecb.

2022-09-06 13:03 UTC, SukkaW approved these changes

2022-09-06 13:05 UTC, merged