fix: cannot find installed module by yarn v3
hexojs/hexo-renderer-markdown-it pull request #199
Opened 2023-05-22 20:55 UTC by dimaslanjaka

fixed cannot find some modules which installed by yarn berry.

error logs before fixed:
```log
ERROR Plugin load failed: hexo-renderers
Error: Cannot find module 'markdown-it-table-of-contents'
Require stack:
- D:\Repositories\hexo-renderers\lib\dist\markdown-it\renderer.js
- D:\Repositories\hexo-renderers\lib\dist\renderer-markdown-it.js
- D:\Repositories\hexo-renderers\lib\dist\renderer-loader.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at D:\Repositories\hexo-renderers\lib\dist\markdown-it\renderer.js:38:39
    at Array.reduce (<anonymous>)
    at new Renderer (D:\Repositories\hexo-renderers\lib\dist\markdown-it\renderer.js:33:35)       
    at rendererMarkdownIt (D:\Repositories\hexo-renderers\lib\dist\renderer-markdown-it.js:103:20)    at D:\Repositories\hexo-renderers\lib\dist\renderer-loader.js:56:9
    at D:\Repositories\hexo-renderers\test\node_modules\hexo\dist\hexo\index.js:272:20
    at tryCatcher (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Repositories\hexo-renderers\test\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
```

2023-05-22 20:58 UTC, dimaslanjaka commented
@yoshinorin review pls, this already tested and working for external plugins installed with yarn berry on monorepo hexo site

2023-05-24 14:27 UTC, yoshinorin requested changes

2023-05-24 14:27 UTC, yoshinorin commented on lib/renderer.js
Don't we have to add `require('path')`?

```js
const path = require('path');
```

2023-05-27 04:44 UTC, dimaslanjaka commented on lib/renderer.js
review again pls

2023-05-27 20:13 UTC, yoshinorin approved these changes
LGTM. Thank you :)

2023-05-27 20:16 UTC, merged